image: "asciidoctor/docker-asciidoctor"

stages:
  - documentation

variables:
  FOOBAR: quux

.setup:
  script:
    - echo creating environment

html:
  stage: documentation
  script:
    - cd doc
    - make
    -
      -
        - make html
        - echo "$PWD"
      -
        - echo "scripts may be in nested arrays"
        - echo "rarely used, but visible with !reference tags"
    # shellcheck will check lower case variables,
    # but ignores all upper case variables
    - echo "$FOOBAR"
    - echo "$FOO"
    - !reference [.setup, script]
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
    paths:
      - doc/*.html
      - doc/assets/

pdf:
  stage: documentation
  script: cd doc; make pdf
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
    paths:
      - doc/*.pdf

epub:
  stage: documentation
  script:
    - cd doc; asciidoctor-epub3 --out-file documentation.epub epub_index.adoc
  artifacts:
    paths:
     - doc/documentation.epub
