spec:
  inputs:
    target:
      type: string
      description: The Target URL
---
trigger:
  stage: .post
  image: $CI_REGISTRY/pipeline-components/helperimages:alpine-utils
  script:
    - |
      curl --location $[[ inputs.target ]]
